spring.application.name=Pandharpur
spring.datasource.url=jdbc:mysql://localhost:3306/assetdb
spring.datasource.username=root
spring.datasource.password=Mahesh7@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


jwt.secret=abcdefghijklmnopqrstuvwxyz1234567890abcdefabcdefabcdefabcdefabcdefabcdefabcdef

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahi224224@gmail.com
spring.mail.password=clhxxpcmkhpfatuc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
